[project]
name = "apple-release-dates"
version = "0.1.0"
description = "Tools to fetch and manage Apple product release dates"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.5",
    "beautifulsoup4>=4.12.2",
    "pandas>=2.2.2",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["apple_release_dates"]

[project.scripts]
dump-apple = "apple_release_dates.dump:cli"
