name: Weekly Update

# Schedule the workflow to run every week
on:
  schedule:
    - cron: '0 0 * * 2,3,6' # Runs every Tuesday, Wednesday, and Saturday at 00:00 UTC, considering Monday, Tuesday, and Friday as days with most releases
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  import-apple-products:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Specify the Python version you need

      # Install dependencies (if required)
      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt

      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install

      # Run your Python script
      - name: Run Python script
        run: |
          python scripts/dump_apple.py
          python scripts/generate_pages.py

      - name: Run pre-commit hooks
        run: pre-commit run --all-files || true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto update source and listing"
          branch: auto-update
          title: "Auto update source and listing"
          body: "This PR is created automatically by GitHub Actions to update the source and listing."
          labels: ["auto-update"]
