name: Weekly Update

# Schedule the workflow to run every week
on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight (UTC)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  import-readwise-highlights:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Specify the Python version you need

      # Install dependencies (if required)
      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt

      # Run your Python script
      - name: Run Python script

        run: |
            python scripts/dump_apple.py
            python scripts/generate_pages.py

      # Commit and push changes
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Auto update source and listing"
            git push
          else
            echo "No changes to commit"
          fi
